// DES FICHIERS DE DÉPENDANCES RÉALISTES, ET CE QU'OSV-SCANNER 2.6.0 EN EXTRAIT.
//
// Chaque fixture mêle ce qu'un vrai projet mêle : un paquet d'un registre
// PUBLIC, un d'un registre PRIVÉ (`acme-internal`), une source git, une source
// locale. `extraction` est ce que le VRAI osv-scanner 2.6.0 en a extrait,
// hors ligne (`--experimental-disable-plugins vulnmatch/osvdev --all-packages`),
// le 4 octobre — recopié tel quel, ordre compris : c'est sur cette liste que la
// porte choisit ce qui part à osv.dev (`aInterroger`).

export interface Verrou {
  /** Le nom du fichier : c'est lui qui dit à l'outil comment le lire. */
  nom: string;
  contenu: string;
  /** `[écosystème, nom, version]`, tels que l'outil réel les a rendus. */
  extraction: readonly (readonly [string, string, string])[];
}

export const VERROUS: Readonly<Record<string, Verrou>> = {
  buildscript: {
    nom: 'buildscript-gradle.lockfile',
    contenu:
      '# This is a Gradle generated file for dependency locking.\n# Manual edits can break the build and are not advised.\n# This file is expected to be part of source control.\ncom.acme.internal:secret:1.0.0=compileClasspath,runtimeClasspath\norg.apache.logging.log4j:log4j-core:2.14.1=compileClasspath,runtimeClasspath\nempty=\n',
    extraction: [
      ['Maven', 'com.acme.internal:secret', '1.0.0'],
      ['Maven', 'org.apache.logging.log4j:log4j-core', '2.14.1'],
    ],
  },
  bun: {
    nom: 'bun.lock',
    contenu:
      '{\n  "lockfileVersion": 1,\n  "workspaces": {\n    "": {\n      "name": "demo",\n      "dependencies": {\n        "@acme-internal/secret-project": "^1.0.0",\n        "local-lib": "file:../local-lib",\n        "minimist": "1.2.0",\n      },\n    },\n  },\n  "packages": {\n    "@acme-internal/secret-project": ["@acme-internal/secret-project@1.0.0", "https://npm.acme-internal.example/@acme-internal/secret-project/-/secret-project-1.0.0.tgz", {}, "sha512-AAAA"],\n    "local-lib": ["local-lib@file:../local-lib", {}],\n    "minimist": ["minimist@1.2.0", "", {}, "sha512-xxxx"],\n  }\n}\n',
    extraction: [
      ['npm', '@acme-internal/secret-project', '1.0.0'],
      ['npm', 'minimist', '1.2.0'],
      ['npm', 'local-lib', ''],
    ],
  },
  cabal: {
    nom: 'cabal.project.freeze',
    contenu:
      'active-repositories: hackage.haskell.org:merge\nconstraints: any.aeson ==1.0.0.0,\n             any.secret-lib ==1.0.0\nindex-state: hackage.haskell.org 2023-01-01T00:00:00Z\n',
    extraction: [
      ['Hackage', 'aeson', '1.0.0.0'],
      ['Hackage', 'secret-lib', '1.0.0'],
    ],
  },
  cargo: {
    nom: 'Cargo.lock',
    contenu:
      '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n\n[[package]]\nname = "demo"\nversion = "0.1.0"\ndependencies = [\n "gitcrate",\n "local-crate",\n "secret-crate",\n "smallvec",\n]\n\n[[package]]\nname = "gitcrate"\nversion = "0.1.0"\nsource = "git+https://github.com/acme-internal/gitcrate#0123456789abcdef0123456789abcdef01234567"\n\n[[package]]\nname = "local-crate"\nversion = "0.1.0"\n\n[[package]]\nname = "secret-crate"\nversion = "1.0.0"\nsource = "registry+https://crates.acme-internal.example/index"\nchecksum = "aaaa"\n\n[[package]]\nname = "smallvec"\nversion = "1.6.0"\nsource = "registry+https://github.com/rust-lang/crates.io-index"\nchecksum = "fe0f37c9e8f3c5a4a66ad655a93c74daac4ad00c441533bf5c6e7990bb42604e"\n',
    extraction: [
      ['crates.io', 'demo', '0.1.0'],
      ['crates.io', 'gitcrate', '0.1.0'],
      ['crates.io', 'local-crate', '0.1.0'],
      ['crates.io', 'secret-crate', '1.0.0'],
      ['crates.io', 'smallvec', '1.6.0'],
    ],
  },
  composer: {
    nom: 'composer.lock',
    contenu:
      '{\n  "_readme": [\n    "x"\n  ],\n  "content-hash": "aaaa",\n  "packages": [\n    {\n      "name": "guzzlehttp/guzzle",\n      "version": "6.0.0",\n      "source": {\n        "type": "git",\n        "url": "https://github.com/guzzle/guzzle.git",\n        "reference": "aaaa"\n      },\n      "dist": {\n        "type": "zip",\n        "url": "https://api.github.com/repos/guzzle/guzzle/zipball/aaaa",\n        "reference": "aaaa",\n        "shasum": ""\n      },\n      "type": "library",\n      "notification-url": "https://packagist.org/downloads/"\n    },\n    {\n      "name": "acme-internal/secret",\n      "version": "1.0.0",\n      "source": {\n        "type": "git",\n        "url": "git@git.acme-internal.example:php/secret.git",\n        "reference": "0123456789abcdef0123456789abcdef01234567"\n      },\n      "type": "library"\n    },\n    {\n      "name": "acme-internal/local",\n      "version": "dev-main",\n      "dist": {\n        "type": "path",\n        "url": "../local",\n        "reference": "bbbb"\n      },\n      "type": "library"\n    }\n  ],\n  "packages-dev": [],\n  "aliases": [],\n  "minimum-stability": "stable",\n  "stability-flags": [],\n  "prefer-stable": false,\n  "prefer-lowest": false,\n  "platform": [],\n  "platform-dev": [],\n  "plugin-api-version": "2.6.0"\n}',
    extraction: [
      ['Packagist', 'acme-internal/secret', '1.0.0'],
      ['Packagist', 'guzzlehttp/guzzle', '6.0.0'],
      ['Packagist', 'acme-internal/local', 'dev-main'],
    ],
  },
  conan: {
    nom: 'conan.lock',
    contenu:
      '{\n  "version": "0.5",\n  "requires": [\n    "zlib/1.2.11#aaaa%1690000000.0",\n    "acme-secret/1.0.0@acme/stable#bbbb%1690000000.0"\n  ],\n  "build_requires": [],\n  "python_requires": []\n}',
    extraction: [
      ['ConanCenter', 'acme-secret', '1.0.0'],
      ['ConanCenter', 'zlib', '1.2.11'],
    ],
  },
  cpm: {
    nom: 'Directory.Packages.props',
    contenu:
      '<Project>\n  <ItemGroup>\n    <PackageVersion Include="Newtonsoft.Json" Version="12.0.1" />\n    <PackageVersion Include="Acme.Internal.Secret" Version="1.0.0" />\n  </ItemGroup>\n</Project>\n',
    extraction: [],
  },
  csproj: {
    nom: 'demo.csproj',
    contenu:
      '<Project Sdk="Microsoft.NET.Sdk">\n  <ItemGroup>\n    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />\n    <PackageReference Include="Acme.Internal.Secret" Version="1.0.0" />\n    <ProjectReference Include="../Local/Local.csproj" />\n  </ItemGroup>\n</Project>\n',
    extraction: [
      ['NuGet', 'Acme.Internal.Secret', '1.0.0'],
      ['NuGet', 'Newtonsoft.Json', '12.0.1'],
    ],
  },
  depsjson: {
    nom: 'app.deps.json',
    contenu:
      '{\n  "runtimeTarget": {\n    "name": ".NETCoreApp,Version=v6.0"\n  },\n  "targets": {\n    ".NETCoreApp,Version=v6.0": {\n      "app/1.0.0": {\n        "dependencies": {\n          "Newtonsoft.Json": "12.0.1"\n        }\n      },\n      "Newtonsoft.Json/12.0.1": {},\n      "Acme.Local/1.0.0": {}\n    }\n  },\n  "libraries": {\n    "app/1.0.0": {\n      "type": "project",\n      "serviceable": false,\n      "sha512": ""\n    },\n    "Newtonsoft.Json/12.0.1": {\n      "type": "package",\n      "serviceable": true,\n      "sha512": "sha512-aaaa",\n      "path": "newtonsoft.json/12.0.1"\n    },\n    "Acme.Local/1.0.0": {\n      "type": "project",\n      "serviceable": false,\n      "sha512": ""\n    }\n  }\n}',
    extraction: [
      ['NuGet', 'Acme.Local', '1.0.0'],
      ['NuGet', 'Newtonsoft.Json', '12.0.1'],
      ['NuGet', 'app', '1.0.0'],
    ],
  },
  gem: {
    nom: 'Gemfile.lock',
    contenu:
      'GIT\n  remote: https://github.com/acme-internal/gitgem.git\n  revision: 0123456789abcdef0123456789abcdef01234567\n  specs:\n    gitgem (0.1.0)\n\nPATH\n  remote: ../localgem\n  specs:\n    localgem (0.0.1)\n\nGEM\n  remote: https://rubygems.org/\n  specs:\n    rack (2.0.0)\n\nGEM\n  remote: https://gems.acme-internal.example/\n  specs:\n    secretgem (1.0.0)\n\nPLATFORMS\n  ruby\n\nDEPENDENCIES\n  gitgem!\n  localgem!\n  rack (= 2.0.0)\n  secretgem\n\nBUNDLED WITH\n   2.4.10\n',
    extraction: [
      ['RubyGems', 'gitgem', '0.1.0'],
      ['RubyGems', 'localgem', '0.0.1'],
      ['RubyGems', 'rack', '2.0.0'],
      ['RubyGems', 'secretgem', '1.0.0'],
    ],
  },
  gemslocked: {
    nom: 'gems.locked',
    contenu:
      'GIT\n  remote: https://github.com/acme-internal/gitgem.git\n  revision: 0123456789abcdef0123456789abcdef01234567\n  specs:\n    gitgem (0.1.0)\n\nPATH\n  remote: ../localgem\n  specs:\n    localgem (0.0.1)\n\nGEM\n  remote: https://rubygems.org/\n  specs:\n    rack (2.0.0)\n\nGEM\n  remote: https://gems.acme-internal.example/\n  specs:\n    secretgem (1.0.0)\n\nPLATFORMS\n  ruby\n\nDEPENDENCIES\n  gitgem!\n  localgem!\n  rack (= 2.0.0)\n  secretgem\n\nBUNDLED WITH\n   2.4.10\n',
    extraction: [
      ['RubyGems', 'gitgem', '0.1.0'],
      ['RubyGems', 'localgem', '0.0.1'],
      ['RubyGems', 'rack', '2.0.0'],
      ['RubyGems', 'secretgem', '1.0.0'],
    ],
  },
  gomod: {
    nom: 'go.mod',
    contenu:
      'module github.com/acme-internal/demo\n\ngo 1.21\n\nrequire (\n\tgolang.org/x/text v0.3.0\n\tgithub.com/acme-internal/secret v1.0.0\n\tgithub.com/acme-internal/local v0.0.0\n)\n\nreplace github.com/acme-internal/local => ../local\n',
    extraction: [
      ['Go', 'github.com/acme-internal/secret', '1.0.0'],
      ['Go', 'golang.org/x/text', '0.3.0'],
      ['Go', '../local', ''],
    ],
  },
  gradle: {
    nom: 'gradle.lockfile',
    contenu:
      '# This is a Gradle generated file for dependency locking.\n# Manual edits can break the build and are not advised.\n# This file is expected to be part of source control.\ncom.acme.internal:secret:1.0.0=compileClasspath,runtimeClasspath\norg.apache.logging.log4j:log4j-core:2.14.1=compileClasspath,runtimeClasspath\nempty=\n',
    extraction: [
      ['Maven', 'com.acme.internal:secret', '1.0.0'],
      ['Maven', 'org.apache.logging.log4j:log4j-core', '2.14.1'],
    ],
  },
  mix: {
    nom: 'mix.lock',
    contenu:
      '%{\n  "gitdep": {:git, "https://github.com/acme-internal/gitdep.git", "0123456789abcdef0123456789abcdef01234567", []},\n  "plug": {:hex, :plug, "1.0.0", "aaaa", [:mix], [], "hexpm", "bbbb"},\n  "secret": {:hex, :secret, "1.0.0", "cccc", [:mix], [], "acme", "dddd"},\n}\n',
    extraction: [
      ['Hex', 'gitdep', ''],
      ['Hex', 'plug', '1.0.0'],
      ['Hex', 'secret', '1.0.0'],
    ],
  },
  'npm-v1': {
    nom: 'package-lock.json',
    contenu:
      '{\n  "name": "demo",\n  "version": "1.0.0",\n  "lockfileVersion": 1,\n  "requires": true,\n  "dependencies": {\n    "minimist": {\n      "version": "1.2.0",\n      "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz",\n      "integrity": "sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ="\n    },\n    "@acme-internal/secret-project": {\n      "version": "1.0.0",\n      "resolved": "https://npm.acme-internal.example/@acme-internal/secret-project/-/secret-project-1.0.0.tgz",\n      "integrity": "sha512-AAAA"\n    },\n    "local-lib": {\n      "version": "file:../local-lib"\n    },\n    "gitdep": {\n      "version": "github:acme-internal/gitdep#0123456789abcdef0123456789abcdef01234567",\n      "from": "github:acme-internal/gitdep"\n    },\n    "parent": {\n      "version": "2.0.0",\n      "resolved": "https://registry.npmjs.org/parent/-/parent-2.0.0.tgz",\n      "dependencies": {\n        "minimist": {\n          "version": "0.0.8",\n          "resolved": "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz"\n        }\n      }\n    }\n  }\n}',
    extraction: [
      ['npm', '@acme-internal/secret-project', '1.0.0'],
      ['GIT', 'https://github.com/acme-internal/gitdep', ''],
      ['npm', 'minimist', '0.0.8'],
      ['npm', 'minimist', '1.2.0'],
      ['npm', 'parent', '2.0.0'],
      ['npm', 'local-lib', ''],
    ],
  },
  'npm-v3': {
    nom: 'package-lock.json',
    contenu:
      '{\n  "name": "demo",\n  "version": "1.0.0",\n  "lockfileVersion": 3,\n  "requires": true,\n  "packages": {\n    "": { "name": "demo", "version": "1.0.0", "dependencies": { "minimist": "1.2.0", "@acme-internal/secret-project": "1.0.0", "local-lib": "file:../local-lib", "gitdep": "github:acme-internal/gitdep#abc" } },\n    "node_modules/minimist": { "version": "1.2.0", "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz", "integrity": "sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ=" },\n    "node_modules/@acme-internal/secret-project": { "version": "1.0.0", "resolved": "https://npm.acme-internal.example/@acme-internal/secret-project/-/secret-project-1.0.0.tgz", "integrity": "sha512-AAAA" },\n    "node_modules/local-lib": { "resolved": "../local-lib", "link": true },\n    "../local-lib": { "name": "local-lib", "version": "0.0.1" },\n    "node_modules/gitdep": { "version": "1.0.0", "resolved": "git+ssh://git@github.com/acme-internal/gitdep.git#0123456789abcdef0123456789abcdef01234567", "integrity": "sha512-BBBB" }\n  }\n}\n',
    extraction: [
      ['npm', '@acme-internal/secret-project', '1.0.0'],
      ['GIT', 'https://github.com/acme-internal/gitdep', '1.0.0'],
      ['npm', 'local-lib', '0.0.1'],
      ['npm', 'minimist', '1.2.0'],
      ['npm', 'local-lib', ''],
    ],
  },
  nuget: {
    nom: 'packages.lock.json',
    contenu:
      '{\n  "version": 1,\n  "dependencies": {\n    "net6.0": {\n      "Newtonsoft.Json": {\n        "type": "Direct",\n        "requested": "[12.0.1, )",\n        "resolved": "12.0.1",\n        "contentHash": "aaaa"\n      },\n      "Acme.Internal.Secret": {\n        "type": "Direct",\n        "requested": "[1.0.0, )",\n        "resolved": "1.0.0",\n        "contentHash": "bbbb"\n      },\n      "Acme.Local": {\n        "type": "Project"\n      }\n    }\n  }\n}',
    extraction: [
      ['NuGet', 'Acme.Internal.Secret', '1.0.0'],
      ['NuGet', 'Newtonsoft.Json', '12.0.1'],
      ['NuGet', 'Acme.Local', ''],
    ],
  },
  pdm: {
    nom: 'pdm.lock',
    contenu:
      '# This file is @generated by PDM.\n# It is not intended for manual editing.\n\n[metadata]\ngroups = ["default"]\nstrategy = ["cross_platform"]\nlock_version = "4.4.1"\ncontent_hash = "sha256:aaaa"\n\n[[package]]\nname = "django"\nversion = "1.11.0"\nsummary = "A high-level Python Web framework"\nfiles = [\n    {file = "Django-1.11-py2.py3-none-any.whl", hash = "sha256:aaaa"},\n]\n\n[[package]]\nname = "gitlib"\nversion = "0.1.0"\ngit = "https://github.com/acme-internal/gitlib.git"\nrevision = "0123456789abcdef0123456789abcdef01234567"\nsummary = ""\n\n[[package]]\nname = "local-lib"\nversion = "0.0.1"\npath = "../local-lib"\nsummary = ""\n\n[[package]]\nname = "secret-lib"\nversion = "1.0.0"\nsummary = ""\nfiles = [\n    {url = "https://pypi.acme-internal.example/x/secret-lib-1.0.0.tar.gz", hash = "sha256:bbbb"},\n]\n',
    extraction: [
      ['PyPI', 'django', '1.11.0'],
      ['PyPI', 'gitlib', '0.1.0'],
      ['PyPI', 'local-lib', '0.0.1'],
      ['PyPI', 'secret-lib', '1.0.0'],
    ],
  },
  pip: {
    nom: 'requirements.txt',
    contenu:
      'django==1.11.0\nflask>=0.1\nsecret-lib==1.0.0\n-e git+https://github.com/acme-internal/gitlib.git@0123456789abcdef0123456789abcdef01234567#egg=gitlib\nlocal-lib @ file:///home/u/local-lib\ngitlib2 @ git+https://github.com/acme-internal/gitlib2.git@main\n./local-lib2\nrequests[security]==2.20.0 ; python_version >= "3"\n',
    extraction: [
      ['PyPI', 'django', '1.11.0'],
      ['PyPI', 'flask', '0.1'],
      ['PyPI', 'requests', '2.20.0'],
      ['PyPI', 'secret-lib', '1.0.0'],
    ],
  },
  'pip-index': {
    nom: 'requirements.txt',
    contenu:
      '--extra-index-url https://pypi.acme-internal.example/simple\ndjango==1.11.0\nsecret-lib==1.0.0\n',
    extraction: [
      ['PyPI', 'django', '1.11.0'],
      ['PyPI', 'secret-lib', '1.0.0'],
    ],
  },
  pipenv: {
    nom: 'Pipfile.lock',
    contenu:
      '{\n  "_meta": {\n    "hash": {\n      "sha256": "aaaa"\n    },\n    "pipfile-spec": 6,\n    "requires": {\n      "python_version": "3.8"\n    },\n    "sources": [\n      {\n        "name": "pypi",\n        "url": "https://pypi.org/simple",\n        "verify_ssl": true\n      },\n      {\n        "name": "acme",\n        "url": "https://pypi.acme-internal.example/simple",\n        "verify_ssl": true\n      }\n    ]\n  },\n  "default": {\n    "django": {\n      "hashes": [\n        "sha256:aaaa"\n      ],\n      "index": "pypi",\n      "version": "==1.11.0"\n    },\n    "secret-lib": {\n      "hashes": [\n        "sha256:bbbb"\n      ],\n      "index": "acme",\n      "version": "==1.0.0"\n    },\n    "gitlib": {\n      "git": "https://github.com/acme-internal/gitlib.git",\n      "ref": "0123456789abcdef0123456789abcdef01234567"\n    },\n    "local-lib": {\n      "editable": true,\n      "path": "../local-lib"\n    }\n  },\n  "develop": {\n    "pytest": {\n      "hashes": [\n        "sha256:cccc"\n      ],\n      "version": "==3.0.0"\n    }\n  }\n}',
    extraction: [
      ['PyPI', 'django', '1.11.0'],
      ['PyPI', 'pytest', '3.0.0'],
      ['PyPI', 'secret-lib', '1.0.0'],
    ],
  },
  pkgconfig: {
    nom: 'packages.config',
    contenu:
      '<?xml version="1.0" encoding="utf-8"?>\n<packages>\n  <package id="Newtonsoft.Json" version="12.0.1" targetFramework="net48" />\n  <package id="Acme.Internal.Secret" version="1.0.0" targetFramework="net48" />\n</packages>\n',
    extraction: [
      ['NuGet', 'Acme.Internal.Secret', '1.0.0'],
      ['NuGet', 'Newtonsoft.Json', '12.0.1'],
    ],
  },
  pnpm: {
    nom: 'pnpm-lock.yaml',
    contenu:
      "lockfileVersion: '9.0'\n\nsettings:\n  autoInstallPeers: true\n  excludeLinksFromLockfile: false\n\nimporters:\n\n  .:\n    dependencies:\n      '@acme-internal/secret-project':\n        specifier: ^1.0.0\n        version: 1.0.0\n      gitdep:\n        specifier: github:acme-internal/gitdep#main\n        version: https://codeload.github.com/acme-internal/gitdep/tar.gz/0123456789abcdef0123456789abcdef01234567\n      local-lib:\n        specifier: file:../local-lib\n        version: file:../local-lib\n      minimist:\n        specifier: 1.2.0\n        version: 1.2.0\n\npackages:\n\n  '@acme-internal/secret-project@1.0.0':\n    resolution: {integrity: sha512-AAAA, tarball: https://npm.acme-internal.example/@acme-internal/secret-project/-/secret-project-1.0.0.tgz}\n\n  gitdep@https://codeload.github.com/acme-internal/gitdep/tar.gz/0123456789abcdef0123456789abcdef01234567:\n    resolution: {tarball: https://codeload.github.com/acme-internal/gitdep/tar.gz/0123456789abcdef0123456789abcdef01234567}\n    version: 1.0.0\n\n  local-lib@file:../local-lib:\n    resolution: {directory: ../local-lib, type: directory}\n    version: 0.0.1\n\n  minimist@1.2.0:\n    resolution: {integrity: sha512-xxxx}\n\nsnapshots:\n\n  '@acme-internal/secret-project@1.0.0': {}\n\n  gitdep@https://codeload.github.com/acme-internal/gitdep/tar.gz/0123456789abcdef0123456789abcdef01234567: {}\n\n  local-lib@file:../local-lib: {}\n\n  minimist@1.2.0: {}\n",
    extraction: [
      ['npm', '@acme-internal/secret-project', '1.0.0'],
      ['GIT', 'https://github.com/acme-internal/gitdep', '1.0.0'],
      ['npm', 'local-lib', '0.0.1'],
      ['npm', 'minimist', '1.2.0'],
    ],
  },
  poetry: {
    nom: 'poetry.lock',
    contenu:
      '# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.\n\n[[package]]\nname = "django"\nversion = "1.11.0"\ndescription = "A high-level Python Web framework"\noptional = false\npython-versions = "*"\nfiles = [\n    {file = "Django-1.11-py2.py3-none-any.whl", hash = "sha256:aaaa"},\n]\n\n[[package]]\nname = "gitlib"\nversion = "0.1.0"\ndescription = ""\noptional = false\npython-versions = "*"\nfiles = []\n\n[package.source]\ntype = "git"\nurl = "https://github.com/acme-internal/gitlib.git"\nreference = "HEAD"\nresolved_reference = "0123456789abcdef0123456789abcdef01234567"\n\n[[package]]\nname = "local-lib"\nversion = "0.0.1"\ndescription = ""\noptional = false\npython-versions = "*"\nfiles = []\ndevelop = true\n\n[package.source]\ntype = "directory"\nurl = "../local-lib"\n\n[[package]]\nname = "secret-lib"\nversion = "1.0.0"\ndescription = ""\noptional = false\npython-versions = "*"\nfiles = []\n\n[package.source]\ntype = "legacy"\nurl = "https://pypi.acme-internal.example/simple"\nreference = "acme"\n\n[metadata]\nlock-version = "2.0"\npython-versions = "^3.8"\ncontent-hash = "aaaa"\n',
    extraction: [
      ['PyPI', 'django', '1.11.0'],
      ['PyPI', 'gitlib', '0.1.0'],
      ['PyPI', 'local-lib', '0.0.1'],
      ['PyPI', 'secret-lib', '1.0.0'],
    ],
  },
  pom: {
    nom: 'pom.xml',
    contenu:
      '<project xmlns="http://maven.apache.org/POM/4.0.0">\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>com.acme</groupId><artifactId>demo</artifactId><version>1.0</version>\n  <dependencies>\n    <dependency><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-core</artifactId><version>2.14.1</version></dependency>\n    <dependency><groupId>com.acme.internal</groupId><artifactId>secret</artifactId><version>1.0.0</version></dependency>\n    <dependency><groupId>com.acme.internal</groupId><artifactId>localjar</artifactId><version>0.0.1</version><scope>system</scope><systemPath>${project.basedir}/lib/local.jar</systemPath></dependency>\n  </dependencies>\n</project>\n',
    extraction: [
      ['Maven', 'com.acme.internal:localjar', '0.0.1'],
      ['Maven', 'com.acme.internal:secret', '1.0.0'],
      ['Maven', 'org.apache.logging.log4j:log4j-core', '2.14.1'],
    ],
  },
  pub: {
    nom: 'pubspec.lock',
    contenu:
      '# Generated by pub\n# See https://dart.dev/tools/pub/glossary#lockfile\npackages:\n  gitpkg:\n    dependency: "direct main"\n    description:\n      path: "."\n      ref: main\n      resolved-ref: "0123456789abcdef0123456789abcdef01234567"\n      url: "https://github.com/acme-internal/gitpkg.git"\n    source: git\n    version: "0.1.0"\n  http:\n    dependency: "direct main"\n    description:\n      name: http\n      sha256: "aaaa"\n      url: "https://pub.dev"\n    source: hosted\n    version: "0.13.0"\n  localpkg:\n    dependency: "direct main"\n    description:\n      path: "../localpkg"\n      relative: true\n    source: path\n    version: "0.0.1"\n  secretpkg:\n    dependency: "direct main"\n    description:\n      name: secretpkg\n      sha256: "bbbb"\n      url: "https://pub.acme-internal.example"\n    source: hosted\n    version: "1.0.0"\nsdks:\n  dart: ">=3.0.0 <4.0.0"\n',
    extraction: [
      ['Pub', 'gitpkg', '0.1.0'],
      ['Pub', 'http', '0.13.0'],
      ['Pub', 'localpkg', '0.0.1'],
      ['Pub', 'secretpkg', '1.0.0'],
    ],
  },
  pylock: {
    nom: 'pylock.toml',
    contenu:
      'lock-version = "1.0"\ncreated-by = "pip"\n\n[[packages]]\nname = "django"\nversion = "1.11.0"\nindex = "https://pypi.org/simple"\nwheels = [{url = "https://files.pythonhosted.org/packages/x/Django-1.11-py2.py3-none-any.whl", hashes = {sha256 = "aaaa"}}]\n\n[[packages]]\nname = "secret-lib"\nversion = "1.0.0"\nindex = "https://pypi.acme-internal.example/simple"\nsdist = {url = "https://pypi.acme-internal.example/x/secret-lib-1.0.0.tar.gz", hashes = {sha256 = "bbbb"}}\n\n[[packages]]\nname = "gitlib"\nvcs = {type = "git", url = "https://github.com/acme-internal/gitlib.git", commit-id = "0123456789abcdef0123456789abcdef01234567"}\n\n[[packages]]\nname = "local-lib"\ndirectory = {path = "../local-lib"}\n',
    extraction: [
      ['PyPI', 'django', '1.11.0'],
      ['PyPI', 'gitlib', ''],
      ['PyPI', 'secret-lib', '1.0.0'],
      ['PyPI', 'local-lib', ''],
    ],
  },
  renv: {
    nom: 'renv.lock',
    contenu:
      '{\n  "R": {\n    "Version": "4.3.0",\n    "Repositories": [\n      {\n        "Name": "CRAN",\n        "URL": "https://cloud.r-project.org"\n      }\n    ]\n  },\n  "Packages": {\n    "jsonlite": {\n      "Package": "jsonlite",\n      "Version": "1.8.0",\n      "Source": "Repository",\n      "Repository": "CRAN"\n    },\n    "secretpkg": {\n      "Package": "secretpkg",\n      "Version": "1.0.0",\n      "Source": "Repository",\n      "Repository": "ACME"\n    },\n    "gitpkg": {\n      "Package": "gitpkg",\n      "Version": "0.1.0",\n      "Source": "GitHub",\n      "RemoteType": "github",\n      "RemoteUsername": "acme-internal",\n      "RemoteRepo": "gitpkg",\n      "RemoteSha": "0123456789abcdef0123456789abcdef01234567"\n    },\n    "localpkg": {\n      "Package": "localpkg",\n      "Version": "0.0.1",\n      "Source": "Local",\n      "RemoteType": "local",\n      "RemoteUrl": "../localpkg"\n    }\n  }\n}',
    extraction: [['CRAN', 'jsonlite', '1.8.0']],
  },
  reqdev: {
    nom: 'requirements-dev.txt',
    contenu: 'django==1.11.0\n',
    extraction: [['PyPI', 'django', '1.11.0']],
  },
  shrinkwrap: {
    nom: 'npm-shrinkwrap.json',
    contenu:
      '{\n  "name": "demo",\n  "version": "1.0.0",\n  "lockfileVersion": 3,\n  "requires": true,\n  "packages": {\n    "": { "name": "demo", "version": "1.0.0", "dependencies": { "minimist": "1.2.0", "@acme-internal/secret-project": "1.0.0", "local-lib": "file:../local-lib", "gitdep": "github:acme-internal/gitdep#abc" } },\n    "node_modules/minimist": { "version": "1.2.0", "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz", "integrity": "sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ=" },\n    "node_modules/@acme-internal/secret-project": { "version": "1.0.0", "resolved": "https://npm.acme-internal.example/@acme-internal/secret-project/-/secret-project-1.0.0.tgz", "integrity": "sha512-AAAA" },\n    "node_modules/local-lib": { "resolved": "../local-lib", "link": true },\n    "../local-lib": { "name": "local-lib", "version": "0.0.1" },\n    "node_modules/gitdep": { "version": "1.0.0", "resolved": "git+ssh://git@github.com/acme-internal/gitdep.git#0123456789abcdef0123456789abcdef01234567", "integrity": "sha512-BBBB" }\n  }\n}\n',
    extraction: [
      ['npm', '@acme-internal/secret-project', '1.0.0'],
      ['GIT', 'https://github.com/acme-internal/gitdep', '1.0.0'],
      ['npm', 'local-lib', '0.0.1'],
      ['npm', 'minimist', '1.2.0'],
      ['npm', 'local-lib', ''],
    ],
  },
  stack: {
    nom: 'stack.yaml.lock',
    contenu:
      'packages:\n- completed:\n    hackage: aeson-1.0.0.0@sha256:aaaa,1000\n    pantry-tree:\n      sha256: bbbb\n      size: 100\n  original:\n    hackage: aeson-1.0.0.0\n- completed:\n    commit: 0123456789abcdef0123456789abcdef01234567\n    git: https://github.com/acme-internal/secret.git\n    name: secret\n    pantry-tree:\n      sha256: cccc\n      size: 100\n    version: 1.0.0\n  original:\n    commit: 0123456789abcdef0123456789abcdef01234567\n    git: https://github.com/acme-internal/secret.git\nsnapshots:\n- completed:\n    sha256: dddd\n    size: 100\n    url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/0.yaml\n  original: lts-20.0\n',
    extraction: [['Hackage', 'aeson', '1.0.0.0']],
  },
  swift: {
    nom: 'Package.resolved',
    contenu:
      '{\n  "pins": [\n    {\n      "identity": "swift-nio",\n      "kind": "remoteSourceControl",\n      "location": "https://github.com/apple/swift-nio.git",\n      "state": {\n        "revision": "aaaa",\n        "version": "2.40.0"\n      }\n    },\n    {\n      "identity": "secret",\n      "kind": "remoteSourceControl",\n      "location": "git@git.acme-internal.example:ios/secret.git",\n      "state": {\n        "revision": "0123456789abcdef0123456789abcdef01234567",\n        "version": "1.0.0"\n      }\n    },\n    {\n      "identity": "local",\n      "kind": "localSourceControl",\n      "location": "/Users/u/local",\n      "state": {\n        "revision": "bbbb",\n        "version": "0.0.1"\n      }\n    }\n  ],\n  "version": 2\n}',
    extraction: [
      ['SwiftURL', '/Users/u/local', '0.0.1'],
      ['SwiftURL', 'git@git.acme-internal.example:ios/secret', '1.0.0'],
      ['SwiftURL', 'github.com/apple/swift-nio', '2.40.0'],
    ],
  },
  uv: {
    nom: 'uv.lock',
    contenu:
      'version = 1\nrequires-python = ">=3.8"\n\n[[package]]\nname = "demo"\nversion = "0.1.0"\nsource = { editable = "." }\ndependencies = [\n    { name = "django" },\n]\n\n[[package]]\nname = "django"\nversion = "1.11.0"\nsource = { registry = "https://pypi.org/simple" }\nsdist = { url = "https://files.pythonhosted.org/packages/x/Django-1.11.tar.gz", hash = "sha256:aaaa", size = 1 }\n\n[[package]]\nname = "gitlib"\nversion = "0.1.0"\nsource = { git = "https://github.com/acme-internal/gitlib.git?rev=main#0123456789abcdef0123456789abcdef01234567" }\n\n[[package]]\nname = "local-lib"\nversion = "0.0.1"\nsource = { directory = "../local-lib" }\n\n[[package]]\nname = "secret-lib"\nversion = "1.0.0"\nsource = { registry = "https://pypi.acme-internal.example/simple" }\nsdist = { url = "https://pypi.acme-internal.example/x/secret-lib-1.0.0.tar.gz", hash = "sha256:bbbb", size = 1 }\n',
    extraction: [
      ['PyPI', 'demo', '0.1.0'],
      ['PyPI', 'django', '1.11.0'],
      ['PyPI', 'gitlib', '0.1.0'],
      ['PyPI', 'local-lib', '0.0.1'],
      ['PyPI', 'secret-lib', '1.0.0'],
    ],
  },
  'yarn-berry': {
    nom: 'yarn.lock',
    contenu:
      '# This file is generated by running "yarn install" inside your project.\n# Manual changes might be lost - proceed with caution!\n\n__metadata:\n  version: 6\n  cacheKey: 8\n\n"@acme-internal/secret-project@npm:^1.0.0":\n  version: 1.0.0\n  resolution: "@acme-internal/secret-project@npm:1.0.0"\n  checksum: abc\n  languageName: node\n  linkType: hard\n\n"demo@workspace:.":\n  version: 0.0.0-use.local\n  resolution: "demo@workspace:."\n  languageName: unknown\n  linkType: soft\n\n"gitdep@github:acme-internal/gitdep#main":\n  version: 1.0.0\n  resolution: "gitdep@https://github.com/acme-internal/gitdep.git#commit=0123456789abcdef0123456789abcdef01234567"\n  languageName: node\n  linkType: hard\n\n"local-lib@file:../local-lib::locator=demo%40workspace%3A.":\n  version: 0.0.1\n  resolution: "local-lib@file:../local-lib#../local-lib::hash=abc&locator=demo%40workspace%3A."\n  languageName: node\n  linkType: hard\n\n"minimist@npm:1.2.0":\n  version: 1.2.0\n  resolution: "minimist@npm:1.2.0"\n  checksum: def\n  languageName: node\n  linkType: hard\n',
    extraction: [
      ['npm', '@acme-internal/secret-project', '1.0.0'],
      ['GIT', 'https://github.com/acme-internal/gitdep', '1.0.0'],
      ['npm', 'local-lib', '0.0.1'],
      ['npm', 'minimist', '1.2.0'],
    ],
  },
  'yarn-v1': {
    nom: 'yarn.lock',
    contenu:
      '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n"@acme-internal/secret-project@^1.0.0":\n  version "1.0.0"\n  resolved "https://npm.acme-internal.example/@acme-internal/secret-project/-/secret-project-1.0.0.tgz#abc"\n  integrity sha512-AAAA\n\n"gitdep@github:acme-internal/gitdep#main":\n  version "1.0.0"\n  resolved "https://codeload.github.com/acme-internal/gitdep/tar.gz/0123456789abcdef0123456789abcdef01234567"\n\n"local-lib@file:../local-lib":\n  version "0.0.1"\n\nminimist@1.2.0, minimist@^1.2.0:\n  version "1.2.0"\n  resolved "https://registry.yarnpkg.com/minimist/-/minimist-1.2.0.tgz#a35008b20f41383eec1fb914f4cd5df79a264284"\n  integrity sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ=\n',
    extraction: [
      ['npm', '@acme-internal/secret-project', '1.0.0'],
      ['GIT', 'https://github.com/acme-internal/gitdep', '1.0.0'],
      ['npm', 'local-lib', '0.0.1'],
      ['npm', 'minimist', '1.2.0'],
    ],
  },
};
